### ISSUE TITLE
Add docker scout output

### ISSUE THREAD

**Issue by plutov** [ajayd-san/gomanagedocker#1]
Would be nice to show Docker Scout output https://packagemain.tech/p/identifying-container-image-vulnerabilities

**Comment by ajayd-san** [comment]
Hey, 

That could be a cool feature to add!!

I'm assuming showing the output of  `docker scout quickview` (neatly formatted and in a popup) is what you are suggesting?

**Comment by plutov** [comment]
@ajayd-san exactly.

**Comment by ajayd-san** [comment]
@plutov Hey, I've added the ability to perform `docker scout quickview` in version v1.1.1.  Go try it out and let me know how it is!

You can install the latest release using the install script. 

```
bash -c "$(curl -sLo- https://raw.githubusercontent.com/ajayd-san/gomanagedocker/main/install.sh)"
```
