### ISSUE TITLE
Chore: removing debug statements

### ISSUE THREAD

**Issue by ajayd-san** [ajayd-san/gomanagedocker#22]
There are multiple `log.Println(...)` statements. For instance: https://github.com/ajayd-san/gomanagedocker/blob/35cca7a367ce3cad70ecbe81fb944ba484f3eb2e/tui/mainModel.go#L343 

They were for debugging initially and serve no purpose. 

The plan is the remove them.

**Comment by saeidalz13** [comment]
I can definitely help with this.
I have one question. 
There are 3 instances that you're logging `report` from `PruneImages` method.

Do you want them gone as well?

**Comment by ajayd-san** [comment]
@saeidalz13 can you add link to the part of code you are talking about? 

Thanks

**Comment by saeidalz13** [comment]
Sure!

First Instance:
https://github.com/saeidalz13/gomanagedocker/blob/2a72fef912eacf2b917798c1ef966608a5124a00/tui/mainModel.go#L519-L527

Second Instance:
https://github.com/saeidalz13/gomanagedocker/blob/2a72fef912eacf2b917798c1ef966608a5124a00/tui/mainModel.go#L537-L545

Third Instance:
https://github.com/saeidalz13/gomanagedocker/blob/2a72fef912eacf2b917798c1ef966608a5124a00/tui/mainModel.go#L556-L563

Hope this makes it more clear.

**Comment by ajayd-san** [comment]
Yes! You can take all of them out.

**Comment by saeidalz13** [comment]
Sweet! I'll create a PR now
