### ISSUE TITLE
BUG 🐞: change the order of the  height and width displayed in `WindowTooSmallModel`

### ISSUE THREAD

**Issue by ajayd-san** [ajayd-san/gomanagedocker#28]
**Describe the bug**
Currently, when `WindowTooSmallModel` is active, the `View` method returns window dimensions in order: `height`, `width`.

**To Reproduce**
Run `gmd` and resize the terminal window till you see the 'windowTooSmall' message. 

**Expected behavior**
 When `windowTooSmallModel` is active, the dimensions displayed should be `width` followed by `height`. 

**Screenshots**
![2024-07-20T21:17:28,230468016-04:00](https://github.com/user-attachments/assets/44f16bd0-bc6e-4747-9fcd-1a53217898ba)

**Desktop (please complete the following information):**
 - OS: Platform Independant
 - gmd Version: v1.3.2

**Comment by pithecuse527** [comment]
Hello,
May I take this?

**Comment by ajayd-san** [comment]
Sure, go for it!

**Comment by ajayd-san** [comment]
fixed by #30
