### ISSUE TITLE
Allow the config to be written as a TOML file. 

### ISSUE THREAD

**Issue by Schnellemann** [ajayd-san/gomanagedocker#37]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Configuration in both TOML and YAML since everybody has their own preferences in configuration file formats. 

**Additional context**
Would like to contribute making this.

**Comment by ajayd-san** [comment]
Hey! 
I really don't think this is a good idea as adding support for different config file formats would be a nightmare to manage. And also in case someone has both `toml` and `yaml` config files, it could lead to unintended behaviour depending on which config file was read last.

**Comment by Schnellemann** [comment]
I get your point, but then consider switching to TOML. Alacritty made the switch from yaml to TOML for better readability and tools for checking for errors. I think a tool like this needs to be highly configurable for the different setups that exists. Having sane defaults is great, but allowing configurability lets users help themselves.

**Comment by ajayd-san** [comment]
Thanks for your input, I will consider this in the near future....
