### ISSUE TITLE
BUG 🐞: support aarch64 and no package for Linux ARM

### ISSUE THREAD

**Issue by Chucky2401** [ajayd-san/gomanagedocker#47]
**Describe the bug**
I would like to try the software, but unfortunately, it seems aarch64 is not supported. In the same time, no package are released for Linux arm64.

**To Reproduce**
When I launch it on my RaspberryPi 5, the script informed me that the architecture is not supported.

**Expected behavior**
Support of the aarch64 architecture

**Desktop (please complete the following information):**
 - OS: Debian 12
 - gmd Version: **N/A**
 - RaspberryPi 5

**Additional context**
I tried to force aarch like this:
```shell
if [[ "$arch" == "x86_64" ]]; then
    arch="amd64"
elif [[ "$arch" == "arm"* ]]; then
    arch="arm64"
# Try to force aarch architecture
elif [[ "$arch" == "aarch"* ]]; then
    arch="arm64"
else
    echo -e "${red}❌ Fail install goManageDocker: ${yellow}Unsupported architecture${nc}"
    exit 1
fi
```

But, even with this modification, no package was found:

```shell

░██████╗░░█████╗░███╗░░░███╗░█████╗░███╗░░██╗░█████╗░░██████╗░███████╗██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
 ██╔════╝░██╔══██╗████╗░████║██╔══██╗████╗░██║██╔══██╗██╔════╝░██╔════╝██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
 ██║░░██╗░██║░░██║██╔████╔██║███████║██╔██╗██║███████║██║░░██╗░█████╗░░██║░░██║██║░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝
 ██║░░╚██╗██║░░██║██║╚██╔╝██║██╔══██║██║╚████║██╔══██║██║░░╚██╗██╔══╝░░██║░░██║██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
 ╚██████╔╝╚█████╔╝██║░╚═╝░██║██║░░██║██║░╚███║██║░░██║╚██████╔╝███████╗██████╔╝╚█████╔╝╚█████╔╝██║░╚██╗███████╗██║░░██║
 ░╚═════╝░░╚════╝░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝░╚═════╝░╚══════╝╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝

Downloading gomanagedocker v for linux (arm64)...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     33      0 --:--:-- --:--:-- --:--:--    33
Extracting gomanagedocker...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
🎉 Installation complete!
You can type "gmd" to start!
```

As you can see, it said: `Downloading gomanagedocker v for linux (arm64)...`, no version, because no package exist.

I would like to try to compile myself, but I don't know anything in Go. Could you elaborate your documentation about this? Prerequisites, etc. for someone who don't know Go.

Thanks!

**Comment by Chucky2401** [comment]
I was able to compile it.

I install Go following this: https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-20-04.
Then, I cloned your repository and compile with this command:

```shell
env GDOS=linux GOARCH=arm64 go build -o release/linux_arm64_1.4/"gmd"
```

Finally, I installed the binary into `~/.local/bin` with the below command and run the app.

```shell
install -Dm 755 gmd -t ~/.local/bin
```

It works fine!

![image](https://github.com/user-attachments/assets/94d78efd-dd46-483c-86b4-6aab7dfd5ca7)

**Comment by ajayd-san** [comment]
Hey, 

I'll add arm to install script in the next release!

How was it on arm? Any issues ? (since I didn't test it on there)

Also, You can directly install go binaries using `go install github.com/ajayd-san/gomanagedocker@main`.

**Comment by pie-t-er** [comment]
Hey,

Is it cool if I pick up this issue?

**Comment by ajayd-san** [comment]
Sure! Go for it
