### ISSUE TITLE
BUG 🐞: Change help description for `prune` in images

### ISSUE THREAD

**Issue by ajayd-san** [ajayd-san/gomanagedocker#53]
**Describe the bug**
The description for the `p` key in the `images` tab is set to `prune images` while other tabs have it set to `prune`.  

**To Reproduce**
Run `gmd` and focus on the `Images` tab.

**Expected behavior**
The description for the `p` key should be `prune` instead of `prune images`. 

**Screenshots**
<img width="561" alt="image" src="https://github.com/user-attachments/assets/e6789cbf-bbb8-41ec-b05a-0714a64b2eb6">

**Desktop (please complete the following information):**
 - OS: Platform independent 
 - gmd Version: gmd 1.4

**Additional context**
The code that needs to be changed can be found in [tui/keys](https://github.com/ajayd-san/gomanagedocker/blob/main/tui/keys.go).

**Comment by pie-t-er** [comment]
Hey can I work on this please?

**Comment by ajayd-san** [comment]
yes go for it!
